src/actions/onboard_actions.js
src/tasks/onboard.js
src/tasks/whitelist.js
test/actions/onboard_actions.js
test_cli/test_cli.js

This is consistent with the onboarding amount which is also provided in
eth.

Provide whitelist deposit in eth

---

contracts/Configuration/Fees.sol
contracts/Configuration/Time.sol
contracts/Front/Challenges.sol
contracts/Front/Roles.sol
contracts/Storage/ApolloDepositStore.sol
contracts/Storage/AtlasStakeStore.sol
contracts/Storage/PayoutsStore.sol
test/contracts/front/roles.js
test/contracts/storage/apollo_deposit_store.js
test/contracts/storage/atlas_stake_store.js

I recommend to read PR commit by commit, instead of reading all of it at once. Would be much easier, because PR contains lots of completely separated minor changes.

a bunch of minor fixes and refactorings

---

.babelrc
package.json
src/actions/upload_actions.js
src/errors/errors.js
src/wrappers/blockchain_state_wrapper.js
test/actions/upload_actions.js
test/wrappers/blockchain_state_wrapper.js

Added validation against fee

---

package.json
src/index.js

Add insufficient funds warning to index.

---

src/wrappers/managed_contract_wrapper.js
src/wrappers/managed_ownable_contract_wrapper.js
test/wrappers/challenges_wrapper.js
test/wrappers/fees_wrapper.js
test/wrappers/kyc_whitelist_wrapper.js
test/wrappers/managed_contract_wrapper.js
test/wrappers/managed_ownable_contract_wrapper.js
test/wrappers/payouts_wrapper.js
test/wrappers/roles_wrapper.js
test/wrappers/uploads_wrapper.js

Removed most of the old processTransaction mechanism. Paving the way for a more elegant solution

Preparing for a improved processTransaction mechanism

---

contracts/Front/KycWhitelist.sol
package.json
test/contracts/front/kyc_whitelist.js

Restrict whitelisting deposit amount to be at least 250k AMB;

---

package.json
src/actions/payouts_actions.js
src/wrappers/time_wrapper.js
test/actions/payouts_actions.js
test/wrappers/time_wrapper.js

Add next payout period start timestamp to payouts actions

---

contracts/Configuration/Config.sol
contracts/Front/Challenges.sol
contracts/Front/Roles.sol
contracts/Middleware/Sheltering.sol
contracts/Storage/AtlasStakeStore.sol
contracts/TestHelpers/AtlasStakeStoreMock.sol
src/constants.js
test/contracts/front/challenges.js
test/contracts/front/roles.js
test/contracts/front/sheltering_transfers.js
test/contracts/middleware/sheltering.js
test/contracts/storage/atlas_stake_store.js

Get rid of storage limits

---

contracts/Storage/AtlasStakeStore.sol
contracts/TestHelpers/AtlasStakeStoreMock.sol
package.json
test/contracts/storage/atlas_stake_store.js

Augmented AtlasStakeStore to include an index of nodes grouped by stake;

---

package.json
src/index.js
src/wrappers/bundle_store_wrapper.js
test/wrappers/bundle_store_wrapper.js
test/wrappers/challenges_event_emitter_wrapper.js

bundleStoreWrapper added

---

package.json
src/index.js
src/wrappers/head_wrapper.js
src/wrappers/roles_event_emitter_wrapper.js
test/wrappers/challenges_event_emitter_wrapper.js
test/wrappers/roles_event_emitter_wrapper.js

rolesWrapper added

---

src/actions/onboard_actions.js
src/index.js
src/tasks/retire.js
src/tasks/run.js
src/wrappers/atlas_stake_store_wrapper.js
src/wrappers/roles_wrapper.js
test/actions/onboard_actions.js
test/wrappers/atlas_stake_store_wrapper.js
test/wrappers/roles_wrapper.js
test_cli/test_cli.js

Retirement

---

contracts/Front/Roles.sol
package.json
src/actions/onboard_actions.js
test/actions/onboard_actions.js
test/contracts/front/roles.js

allow Apollo to onboard with any stake

---

contracts/Boilerplate/Context.sol
contracts/BoilerplateTest/MockContext.sol
package.json
src/deployer.js
test/contracts/boilerplate/base.js
test/contracts/boilerplate/context.js
test/wrappers/head_wrapper.js

Added version tag support for context contract;

---

package.json
src/constants.js
src/wrappers/head_wrapper.js
test/wrappers/head_wrapper.js

Throw meaningful error if context is not set in the head contract;

---

package.json
src/actions/upload_actions.js
test/actions/upload_actions.js

upload actions improvement

---

test_gas/gas_benchmark.js

Fixed gas benchmark

---

contracts/Consensus/BlockRewards.sol
package.json
src/wrappers/block_rewards_wrapper.js
test/contracts/consensus/block_rewards.js
test/wrappers/block_rewards_wrapper.js

Note:
Not updated version yet. I guess we will bump version after finishing multisig/multiplexer stuff.

BaseRewardChanged event added

---

package.json
src/actions/multisig_actions.js
src/wrappers/multisig_wrapper.js
test/actions/multisig_actions_integration.js
test/wrappers/multisig_wrapper.js
test_cli/test_cli.js

 Return confirmation counts with transactions. Throw errors when confirmed transaction fails

---

package.json
src/wrappers/head_wrapper.js
test/wrappers/head_wrapper.js

Add getting contracts version to wrapper.

---

package.json
src/wrappers/bundle_store_wrapper.js
test/wrappers/bundle_store_wrapper.js

sheltering events wrappers

---

package.json
src/wrappers/validator_proxy_wrapper.js
test/wrappers/validator_proxy_wrapper.js

Block reward address wrapper added

---

package.json
src/wrappers/atlas_stake_store_wrapper.js
test/wrappers/atlas_stake_store_wrapper.js

getStake and getBasicStake added

---

contracts/Boilerplate/Catalogue.sol
contracts/Front/Payouts.sol
contracts/Front/Uploads.sol
contracts/Storage/PayoutsStore.sol
contracts/Storage/RewardsEventEmitter.sol
src/contract_jsons.js
src/wrappers/rewards_event_emitter_wrapper.js
test/contracts/front/payouts.js
test/contracts/front/upload.js
test/contracts/storage/payouts_store.js
test/wrappers/rewards_event_emitter_wrapper.js

payout withdrawal event

---

contracts/Front/Challenges.sol
contracts/Front/DmpAtlasSelectionBase.sol
contracts/Front/DmpBasedDesignator.sol
contracts/Front/ShelteringTransfers.sol
contracts/Storage/ShelteringTransfersStore.sol
package.json
src/index.js
src/wrappers/challenge_wrapper.js
src/wrappers/sheltering_transfers_wrapper.js
src/wrappers/transfers_event_emitter_wrapper.js
test/contracts/front/challenges.js
test/contracts/front/sheltering_transfers.js
test/contracts/storage/sheltering_transfers_store.js
test/wrappers/challenges_wrapper.js
test/wrappers/sheltering_transfers_wrapper.js
test/wrappers/transfers_event_emitter_wrapper.js

Upgrade sheltering transfer

---

contracts/Front/Challenges.sol
package.json
src/actions/deploy_actions.js
src/utils/web3_tools.js
test/actions/deploy_action.js

Restore backward compatibility

---

src/wrappers/head_wrapper.js

Added missing 'transfersEventEmitter' name into Head wrapper.

---

package.json
src/wrappers/validator_set_wrapper.js
test/wrappers/validator_set_wrapper.js

Add getValidator method to wrapper

---

contracts/Front/Payouts.sol
package.json
src/index.js
src/wrappers/head_wrapper.js
test/contracts/front/payouts.js

Fix payouts withdraw

---

contracts/Front/ShelteringTransfers.sol
contracts/Storage/ShelteringTransfersStore.sol
package.json
src/actions/deploy_actions.js
src/wrappers/sheltering_transfers_wrapper.js
test/actions/deploy_action.js
test/contracts/storage/sheltering_transfers_store.js
test/wrappers/sheltering_transfers_wrapper.js

Fix sheltering transfer uint64

---

contracts/Front/Payouts.sol
contracts/Middleware/Sheltering.sol
package.json
src/actions/deploy_actions.js
src/wrappers/sheltering_wrapper.js
test/actions/deploy_action.js
test/contracts/front/payouts.js
test/contracts/middleware/sheltering.js
test/wrappers/sheltering_wrapper.js
yarn.lock

Add sheltering reward

---

contracts/Middleware/Sheltering.sol
package.json
test/contracts/middleware/sheltering.js

Fix reward transfer

---

contracts/Front/Payouts.sol
contracts/Middleware/Sheltering.sol
package.json
test/contracts/front/payouts.js
test/contracts/middleware/sheltering.js

Adding method for fix wrong rewards balances.

---

package.json

contract version 69

---

package.json

version 70

---

contracts/Boilerplate/Multiplexer.sol
contracts/Front/Roles.sol
package.json
src/actions/multisig_actions.js
src/index.js
src/wrappers/apollo_deposit_store_wrapper.js
src/wrappers/multiplexer_wrapper.js
test/actions/multisig_actions_integration.js
test/contracts/boilerplate/multiplexer.js
test/contracts/front/roles.js
test/mocha_env.js
test/wrappers/apollo_deposit_store_wrapper.js
test/wrappers/multiplexer_wrapper.js

Add multisig apollo retire

---

contracts/Boilerplate/Multiplexer.sol
contracts/Configuration/Fees.sol
contracts/Front/Roles.sol
contracts/Front/Uploads.sol
package.json
src/actions/multisig_actions.js
src/wrappers/fees_wrapper.js
src/wrappers/multiplexer_wrapper.js
test/contracts/boilerplate/multiplexer.js
test/contracts/configuration/fees.js
test/contracts/front/upload.js

Add developer fee to crypto-economics.

---

contracts/Middleware/Sheltering.sol
package.json
src/wrappers/sheltering_wrapper.js

Remove expired bundles

---

contracts/Front/ShelteringTransfers.sol
package.json

Added cancelation of expired bundles transfers

---

contracts/Middleware/Sheltering.sol
package.json

Added check for bundle expiration from upload timestamp

---

contracts/Middleware/Sheltering.sol
package.json

Added drop bundle functionality

---

contracts/Middleware/Sheltering.sol
package.json

Sending fee for drop bandle to uploader

---

contracts/Front/ShelteringTransfers.sol
contracts/Middleware/Sheltering.sol
package.json

Improving bundle transfer resolve

---

contracts/Pool/Pool.sol

Fix reward calc

---

src/wrappers/bundle_store_wrapper.js

Add getShelterers() and getUploader() to BundleStoreWrapper

---

test/contracts/pool/pool.js
test/contracts/pool/pool_token.js
test/contracts/pool/pools_nodes_manager.js
test/contracts/storage/pool_events_emitter.js
test/contracts/storage/pools_store.js

Pool tests new

---

contracts/Pool/Pool.sol
src/actions/deploy_actions.js
src/actions/pool_actions.js
src/tasks/pooling.js
test/contracts/pool/pool.js

Improve pooling

---

contracts/Storage/PoolsStore.sol
test/contracts/storage/pools_store.js

fix removePool

---

contracts/Storage/PoolsStore.sol
test/contracts/storage/pools_store.js

Fix poolsstore

---

contracts/Boilerplate/Catalogue.sol
contracts/Boilerplate/Context.sol
contracts/Boilerplate/Multiplexer.sol
contracts/Configuration/Fees.sol
contracts/Front/Roles.sol
contracts/Pool/PoolsNodesManager.sol
package.json
src/actions/fees_actions.js
src/actions/multisig_actions.js
src/actions/pool_actions.js
src/tasks/pooling.js
src/utils/web3_tools.js
src/wrappers/fees_wrapper.js
src/wrappers/multiplexer_wrapper.js
test/contracts/pool/pool.js
test/contracts/pool/pools_nodes_manager.js

Migrate to v2
